// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWqEaFgvV6vqidjBk9Lsstjlh6NEXpq5M',
    appId: '1:69800866200:web:333e5372e7389a606c3bed',
    messagingSenderId: '69800866200',
    projectId: 'flash-app-dd160',
    authDomain: 'flash-app-dd160.firebaseapp.com',
    storageBucket: 'flash-app-dd160.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhdCk2f0nb8Myy_XNaCd88WgRzNw90ZM0',
    appId: '1:69800866200:android:be1c65e4d7e1f4de6c3bed',
    messagingSenderId: '69800866200',
    projectId: 'flash-app-dd160',
    storageBucket: 'flash-app-dd160.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV1qxEP2USlMMVrXE4gQ1UQ19jU8TacZE',
    appId: '1:69800866200:ios:22380ab21a2c6b1b6c3bed',
    messagingSenderId: '69800866200',
    projectId: 'flash-app-dd160',
    storageBucket: 'flash-app-dd160.appspot.com',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAV1qxEP2USlMMVrXE4gQ1UQ19jU8TacZE',
    appId: '1:69800866200:ios:31c9c853b73e91dd6c3bed',
    messagingSenderId: '69800866200',
    projectId: 'flash-app-dd160',
    storageBucket: 'flash-app-dd160.appspot.com',
    iosBundleId: 'com.example.flashChat.RunnerTests',
  );
}
